### ISSUE TITLE
An interesting module A9G

### ISSUE THREAD

**Issue by iotong** [espruino/Espruino#1497]
open source address：https://github.com/Ai-Thinker-Open/GPRS_C_SDK
Features:

- RDA 32 bit RISC core, frequency up to 312MHz, with 4k instruction cache, 4k data cache
- Up to 29 GPIOs (with two download pins)
- Calendar (Real Time Clock) with alarm
- 1 USB1.1 device interface
- 2 UART interface with flow control (+1 download/debug serial port)
- 2 SPI interface
- 3 I 2 C interface
- 1 SDMMC controller (interface)
- 2 ADC interface, 10 bits
- 32Mb (4MB) SPI NOR Flash
- 32Mb (4MB) DDR PSRAM
- 8kHz, 13Bits/sample ADC mic
- 48kHz, 16bits/sample DAC Audio
- Power Management Unit: Lithium battery charge management, integrated DC-DC and LDOs, variable IO voltage
- 18.8 x 19.2 mm SMD package
- Quad-band GSM/GPRS (800/900/1800 / 1900MHz)
- calls
- SMS service

If Espruino can run on this module, it will be a matter of how great event.

**Comment by gfwilliams** [comment]
Thanks - definitely looks like it'd be good with Espruino on it.

A port is possible, but right now it's just a question of time. I don't have much time and I have to focus my efforts on things that actually help to bring in money so I can afford to continue to work on Espruino.

Much as with ESP8266/ESP32, nobody is going to pay me anything for Espruino on the A9/A9G because they'll buy cheap modules from wherever they can and install Espruino on them. It makes it hard to justify spending the time on them,
