### ISSUE TITLE
make issue: update a header file does not recompile ....

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1557]
used touch to simulate edit process.

    touch src/jsutils.h              
    make
    make: Nothing to be done for `all'.

    touch src/jsutils.c  
    make
    CC src/jsutils.o
    .....

**Comment by gfwilliams** [comment]
Yeah, you just have to `make clean`... But then you have to `make clean` for lots of the changes, and a full make takes like 20 seconds?

I think the need to `make clean` is documented as well...

Do you have a solution that doesn't make the makefile hugely complicated and hard(er) to maintain?

Otherwise I think we should close this.

**Comment by MaBecker** [comment]
I am fine with that, so lets close it.
