### ISSUE TITLE
SyntaxError in logical expressions fail for some cases 

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1629]
add ( logical expressions ) for this test files 
* test_array_access.js
* test_array_big_indices.js
* test_function_length.js
* test_object_proto.js 
* test_string_match.js

**Comment by gfwilliams** [comment]
How are you uploading? Do you have your own tool?

The issue is the usual Espruino gotcha - if you copy/paste into the REPL then it'll execute after a newline unless there are more open brackets than closed.

If you upload with the Espruino CLI then those line endings get turned into Alt+Enter and it should all work great - so I'm not sure if this is something that we should really be tweaking tests for.

If you want a quick hack to get your own code uploading, just surround everything in `{` and `}`.

**Comment by MaBecker** [comment]
upload like described in #1490

**Comment by MaBecker** [comment]
but tested in console and WebIDE upload too.

**Comment by gfwilliams** [comment]
Thanks - it was a CLI/WebIDE issue - if you use the latest from GitHub it should work now.

It's a good one to fix as I bet that's been tripping people up.
