### ISSUE TITLE
REPL Typo - ReferenceError: ReferenceError: "a" is not defined

### ISSUE THREAD

**Issue by sebi5361** [espruino/Espruino#1716]
With "a" being not defined, typing into the REPL:
```
>try { a; } catch(e) { print(e); }
ReferenceError: ReferenceError: "a" is not defined
=undefined
```
brings a small typo as `ReferenceError:` is duplicated.

**Comment by gfwilliams** [comment]
This is because when printed to the console, the type of the Object gets printed first, followed by the result of `toString`.

Eg:

```
>new Date()  
=Date: Mon Dec 9 2019 09:04:01 GMT+0000
```

Just in this case, `toString` is `ReferenceError: "a" is not defined` as it is in Node.js.

I know it's not perfect, but unless you know something I don't about how stuff is printed to the console, the fix for this minor issue would just be a hack - so I'm closing for now
