### ISSUE TITLE
How to add further display driver in c?

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1778]
I am very impressed about speed of  screen updates on Bangle.js - great work!

Just tried a ili9341 via spi with javascript which is extremely  slow.

As JumJum is working on his EFEU platform it could very easy for all to include selectively  drivers.

This is how I would start:

* choose a c implementation for ili9341
* pull it into .h and .c file
* add ifdefs 
* integrate into graphics?

What else is needed to get it working?

**Comment by gfwilliams** [comment]
Yes, that sounds about right. Worth noting that the ST7789 SPI driver is already in there and will be amazingly similar to the ili9341 (apart from maybe some initialisation info) so it might be worth either using that as a base or ideally just changing it to `spilcd.c` and IFDEFing the relevant bits.

Also Bangle.js's LCD is fast because it's parallel 8 bit. ili9341 will be noticeably faster in C obviously, but it's not going to be as good as Bangle.js
