### ISSUE TITLE
RegExp 'Assertions' not supported

### ISSUE THREAD

**Issue by matjaz** [espruino/Espruino#1853]
I've tried formatting number using regex.

    '1234567.89'.replace(/\B(?=(\d{3})+(?!\d))/g, ",")

which does not work.

**Comment by gfwilliams** [comment]
Thanks, but the Espruino regex docs do clearly say it doesn't contain the full JS regex spec.

PRs are welcome for extra functionality (or just erroring on unsupported stuff), but this is a severely restricted embedded device and the RegExp implementation is meant to handle 95% of what people normally use regex for.

I think for stuff like the thousands separator it's going to be better to just write it in JS code.

**Comment by matjaz** [comment]
yeah. for Bangle it's done here https://github.com/matjaz/BangleApps/commit/fd4e0ceea4f07204a8ba934cc6ccf7a0f9aa99e7#diff-369f213dc47e483871668d8b63615915R184

**Comment by gfwilliams** [comment]
This RegExp seems to use the following that aren't supported yet:

* `x{3}` numeric quantifier
* `\B` Assertion Matches a non-word boundary
* `x(?=y)` Lookahead assertion:
* `x(?!y)` Negative lookahead assertion

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions

Honestly these seem like they're too painful to support in Espruino with maybe the exception of numeric quantifiers.

Rather than having one bug for each of these I'm just going to close this and roll everything into the first of the 3 RegExp issues here

**Comment by gfwilliams** [comment]
rolled into https://github.com/espruino/Espruino/issues/1257
