### ISSUE TITLE
FIFO_FULL error with gpsnav app and gpsrec

### ISSUE THREAD

**Issue by jeffmer** [espruino/Espruino#1859]
I am getting the following error with the gpsnav app on v2.05.179:
```
New interpreter error: FIFO_FULL
Interpreter error: [
  "FIFO_FULL"
 ```
It did not happen with v2.05.104 and I see there was a major change w.r.t. gps handling on the 1st June:
**GPS-raw event ArrayBuffer, handle UBX protocol**
It also happens when you start the GPS recorder. 
The recorder and app both still work, so it may be that FIFO_FULL was happening before and not signalled.

**Comment by gfwilliams** [comment]
Thanks for letting me know. Yes, that's what is happening - basically it wasn't detecting previously when it was having to throw away GPS data, but now it is.

I guess the ideal solution is to ditch the GPS buffer completely and send data using the IO queue...

However it's not actually important because neither of those apps uses the GPS-raw data anyway.

So I think for now the best bet is actually to make Bangle.js not report the error unless something is using GPS raw.
