### ISSUE TITLE
PDU advertisement Type

### ISSUE THREAD

**Issue by seragENTp** [espruino/Espruino#1961]
I'm trying to advertise Heart Rate Measurements using the below code  :
```
var hr = 65;
NRF.setServices({
  0x180D: { // heart_rate
    0x2A37: { // heart_rate_measurement
      notify: true,
      value : [0x06, hr],
    },
    0x2A38: {
      readable: true,
      value: [0x02]
    }
  }
},{advertise:[0x180D]});

NRF.setAdvertising({}, {name:"FLAG",scannable:true,discoverable:true,connectable:true});

setInterval(function () {
  NRF.updateServices({
    0x180D: {
      0x2A37: {
        value: [0x06,Math.floor(Math.random() * 100)],
        notify: true
      }
    }
  });
}, 5000);
```
After investigating the first 4 bits in the PDU header i found out that the advertisement type is 4 (SCAN_RES). Is it possible to change the advertisement type to 0 ( ADV_IND) , the legacy  Connectable Scannable Undirected advertising ?.

Peripheral:  Bangle js (with nRF52832).
Firmware: 2v08.

**Comment by gfwilliams** [comment]
Hi - this is actually expected. Service UUID without data get put in a scan response packet normally, because usually they're 128 bits and then trying to fit them in the main BLE data packet would fail.

Without having a way to explicitly set what goes where it all gets a bit tricky.

The workaround for this is to advertise as normal, but to then manually poke the service data you need on the end of the advertising data:

```
NRF.setAdvertising({}, {name:"FLAG",scannable:true,discoverable:true,connectable:true});
// get normal advertising data
var d = NRF.getAdvertisingData({});
// append service UUID 0x180D
var e = new Uint8Array(d.length+4);
e.set(d);
e.set([3,0x03, 0x0D,0x18],d.length);
// set new advertising data
NRF.setAdvertising(e);
```
