### ISSUE TITLE
(BangleJS 2): Leverage Accelerometer interrupt

### ISSUE THREAD

**Issue by LeonMatthes** [espruino/Espruino#2233]
When looking on the hackaday page of the SMA Q3 (the Hardware that BangleJS2 is based on), we can see two things:
1. The Accelerometer is supposedly a Kionix KX022
2. One of the Accelerometers Interrupt pins is supposedly connected to Pin 39 (D39).

I'm currently looking into getting this interrupt working to enable low-power Tap-to-wake or other functions without having to actively poll the accelerometers registers.

## Current discoveries
So far I have discovered that the hackaday page seems to be correct.
Reading the WHO_AM_I register of the KX022 returns 0x14, which according to the data sheet indicates a KX022, not a KX023, as suggested by the current Espruino code
Furthermore, running this code:
```
function enableInterrupts() {
  Bangle.accelWr(0x18,0x00101100); //disable active mode
  Bangle.accelWr(0x1C,0b110000); // INT1 seems to be on D39
  Bangle.accelWr(0x1F,0b100); // Enable Tap detection
  Bangle.accelWr(0x20,0b010000); // INT 2 is probably not connected
  Bangle.accelWr(0x21,0b000); // disable INT2
  Bangle.accelWr(0x18,0b10101100); //re-enable active mode

  setWatch(()=>console.log("Tap"),D39,false);
}
```
Reveals that INT1 is indeed connected to the D39 pin.
Running enableInterrupts() and then tapping the watch should result in "Tap" being printed to the console.

## Future Work & Open Questions
Ideally, BangleJS2 shouldn't be actively polling the accelerometer when tap-to-wake or twist-to-wake is enabled, but it seems this is currently still the case.
See: https://github.com/espruino/Espruino/blob/984ac383909be40969e1c546840bf41135ceb474/libs/banglejs/jswrap_bangle.c#L1091

With the interrupt line actually being connected on the BangleJS2, this should allow for tap-to-wake, double-tap-to-wake or even twist-to-wake to be implemented with very low power consumption.

I'm somewhat unfamiliar with the current code base, but am willing to contribute (given I find the time :sweat_smile: ).
From what I can currently gather, the `peripheralPollHandler` is called every 80ms (even when the watch is locked?) to ensure no events are missed.
Then does this mean the chip doesn't actually go to sleep/has to wake up that often, even when locked?
That could of course be improved by listening to the interrupt.

I also don't yet know how the step counting works :thinking: 
The KX022 doesn't have a built-in step counter. So that must happen in the watch somewhere.
Possibly this could be optimized as well, as the KX022 has a 256 byte buffer, that could be read in FIFO mode when an interrupt reports it as (almost) full. All 256 bytes could and then processed as a whole, which should also be more efficient.

I would appreciate any feedback and input on where to get started, and what the current needs of the community for these features is.
Personally, I would love to use double-tap-to-wake, as I think that would be quicker/more natural than to fiddle with the button.

**Comment by gfwilliams** [comment]
Hi - interesting about the KX022 (I think because Bangle.js 1 was KX023 and they're pretty much compatible, I just assumed).

The issue with IRQs is that Bangle.js has to wake up every so often anyway - for instance to kick the watchdog, toggle EXTCOMIN on the LCD (which *has* to be done or we get burn-in), HRM and Compass (if on) and other housekeeping. Wake on twist and step counting are handled in software (and wake on twist needs to respond reasonably quickly), so about the only one that would really benefit from this is tap to wake.

peripheralPollHandler is called every 80ms normally, but when the watch hasn't been moved for a while (eg it's on a desk) the poll interval drops to 800ms. Power usage goes from 0.3mA to 0.15mA. **Even at the higher rate of 0.3mA that's around 30 days battery life** - so further improvements on that are unlikely to affect many people (a clock face updating once a second uses *way* more battery)

So in a way it doesn't really matter that we're not using the IRQ line. Using the FIFO could be neat though as we could potentially drop the poll interval to maybe 4 times a second (from 12) unless the compass was on and then just process the accelerometer data as it came in (however there is a high speed accelerometer recorder app which uses the FIFO which would break if we started using in in the firmware).

Other thing to note is I can pretty much guarantee we'd get complaints about the 'screen flicker' from the lower poll interval toggling EXTCOMIN less often :(

So honestly, I'm not sure if it's really worth the hassle for the relatively small battery life improvement for most people - especially as it would make the things that were done in software a bit more sluggish (like the twist to wake or button long-press to go home).

But the double tap to wake would definitely be a good addition, and could be implemented really easily by adding another flag that's handled a bit like JSBF_WAKEON_TOUCH (JSBF_WAKEON_DOUBLETAP?)

**Comment by LeonMatthes** [comment]
Hm, okay, this is a bit of a different situation than I expected :)

A few things for the sake of my understanding:

The watchdog is only watching for a looooong press of the button of > 10s to then reboot, right?
So couldn't the watchdog be enabled/disabled by HW interrupt as well?
I.e. if we measure a rising flank enable the watchdog timer, on a falling flank disable it again. There's no point in having it on when the button isn't even pressed, right?

Also, couldn't the "wake on twist" be implemented in HW on the accelerometer?
It does seem to have a "wake on motion" interrupt, so the "wake on twist" algorithm could also be triggered by the accelerometer interrupt. This could also possibly be faster to unlock, as we don't have to wait for the 80ms polling interval, but get an immediate interrupt in hardware.

That still leaves the EXTCOMIN to toggle on an interval. But at least the background work could be reduced and potentially made more responsive as well, as an interrupt could potentially react quicker than a 80ms interval poll.

In any case, just something to consider, maybe I can at least find some time to implement the double-tap w/ interrupt.

**Comment by gfwilliams** [comment]
> So couldn't the watchdog be enabled/disabled by HW interrupt as well?

The point of the watchdog is to stop you bricking the Bangle if the firmware breaks. If the software stopped doing what it was supposed to (hardfault, brownout, etc), you'd potentially have to wait up to a month for the battery to run down before you could even restart it into the bootloader to update new firmware. To avoid that, the watchdog cannot be turned off once enabled - it's a hardware thing.

> Also, couldn't the "wake on twist" be implemented in HW on the accelerometer?

Maybe, yes. It's just we had a working solution from Bangle.js 1 which I didn't see a reason to change.

> This could also possibly be faster to unlock, as we don't have to wait for the 80ms polling interval

True - I don't know if 40ms average delay in wakeup would be *that* noticeable but it would definitely help.

**My point is in theory IRQ would help, but there are a lot of things that would need changing before it actually gave you better power usage**. Just adding IRQ on top of everything else may even slightly *increase* power usage.

> maybe I can at least find some time to implement the double-tap w/ interrupt.

That would be great, but if you do that please could you also get the single tap working with it too?

I'd also have some concerns about power usage... I guess you wouldn't have a way to check yourself unless you are willing to sacrifice a Bangle? If something happens like a pullup gets configured when it shouldn't be there, that alone could double power usage even from the 0.3mA it is in it's highest power draw state. And it's not just when it's running - configuring the hardware wrong can make it drain the battery faster even when everything is meant to be off.
