### ISSUE TITLE
Promise.all - Uncaught Error: Unhandled promise rejection: Error: Unknown argspec 32864

### ISSUE THREAD

**Issue by philipandresen** [espruino/Espruino#2377]
Minimal-ish Reproduction code in the web IDE:
```
const x = new Promise((resolve, reject) => {
  setTimeout(() => resolve(console.log("Hello")), 1000);
});

const y = new Promise((resolve, reject) => {
  setTimeout(() => resolve(console.log("World")), 1000);
});

Promise.all([x,y]).then(() => console.log("Done!"));
```
full output:
```
>
 ____                 _
|  __|___ ___ ___ _ _|_|___ ___
|  __|_ -| . |  _| | | |   | . |
|____|___|  _|_| |___|_|_|_|___|
         |_| espruino.com
 2v18.1 (c) 2021 G.Williams
>
>
Hello
Uncaught Error: Unhandled promise rejection: Error: Unknown argspec 32864
World
Uncaught Error: Unhandled promise rejection: Error: Unknown argspec 32864
>
```
Seems to be coming from : https://github.com/espruino/Espruino/blob/c660ebe1bca31178990f1072ddb5ccf5e0251b24/scripts/build_jswrapper.py#L803

But actual root cause unknown. Would you believe I don't really know python either? I can prod it a little later, but blood sugar is the limiting factor at the moment.

Just encountered this when converting an app I wrote to be async, and then I needed to get a screenshot. 

Runs fine on the watch, though [BangleJs2]. It just can't run on the emulator!

EDIT:  `Promise.all([]).then(() => console.log("Done!"));` works fine in both. Seems to only complain when you put an actual promise in there.

**Comment by gfwilliams** [comment]
Ahh, right - so this is the emulator?

The issue is we have to have a way to call arbitrary functions from the interpreter. Usually this can be done in a magic way by in Emscripten it seems we can only do it easily  by having every possible format of arguments that might be used implemented in a giant switch statement. We do that by scanning all defined functions, but it looks like Promises have a different type - we'll have to add that argspec in manually
