### ISSUE TITLE
.join`` doesn't work

### ISSUE THREAD

**Issue by KTibow** [espruino/Espruino#2475]
```
[1, 2].join("") // works fine
[1, 2].join`` // works fine in browsers but not in espruino, should be "12", instead is ""
```

**Comment by gfwilliams** [comment]
Ok, I just looked this up and it's JS's 'Tagged Templates': https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates

Do you have a legitimate use for this feature?

Because honestly this looks like one of those bits of JS spec that seems really clunky - so I'm tempted just to ensure that Espruino errors rather than bloating it with a feature that I don't believe many people will use.

**Comment by gfwilliams** [comment]
Ok, cool. Just added
