### ISSUE TITLE
asm.js support

### ISSUE THREAD

**Issue by maks** [espruino/Espruino#332]
I spotted http://forum.espruino.com/conversations/957/#comment13946 (sorry I can't seem to login to the forums right now) but my idea was about using asm.js (https://github.com/dherman/asm.js/) as the "inline assembly" in Espruino.

What I had in mind was given that asm.js is a nice simple subset of JS, to write a basic compiler for it into ARM assembly and then have an ARM assembler assemble that into ARM machine code that code be poked into flash and then called as @gfwilliams you suggested in that forum comment.

I realise that the ARM instruction set is not that small or simple and I've not done ARM assembly before, so I was going to first try prototyping this approach on AVR instead, where there's a much smaller/simpler 8bit instruction set and someone has already written a working assembler in JS (https://github.com/tadpol/Avrian-Jump) to get me started. And with AVR, especially the smaller ones, theres not much chance of getting the espruino js interpreter running but I'd still like to be writing JS for them using the excellent espruino WebIDE chrome app and maybe even getting support for the stk200 protocol into the webide to get arduino uploads working from it too :-)

Talking about "poking" and 8bit assembly, this would kind of be like the old school assembly/machine lang approach from the old 6502/z80 days as was described in the excellent Usborne book:  https://boingboing.net/2013/05/16/1983s-wonderful-introducti.html  though perhaps I'm the only one here old enough to remember the bbc/vic20/c64 days :-)

**Comment by gfwilliams** [comment]
I think you've noticed this now, but there is now: http://www.espruino.com/Compilation

With more work on the compiler (details in that page), it could keep track of variable types and could then perform integer operations as native instructions (rather than passing them off to `jsvMathsOp`).

Closing this, so we can keep track of it [on this issue](https://github.com/espruino/EspruinoTools/issues/9) in EspruinoTools
