### ISSUE TITLE
Warn about extra elements in initialiser object

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#413]
For things like SPI.setup it's easy to misspell something and then that argument is ignored silently.

We could probably create a general purpose function that got elements from an object and then warned if it got any that it wasn't expecting.

**Comment by SpenceKonde** [comment]
ARGH!

I had been using I2C.setup({... baud:200000}) for months... and it's not called baud for I2C....

After setting baud and seeing that it was still just as slow, I incorrectly concluded that the bottleneck was elsewhere, and put a lot of coding effort into speeding up other parts (at considerable cost in maintainability and memory). Just now, though someone mentions in Gitter that it's not called baud for I2C.... I go in and change it to bitrate - and sure enough, now it's faster (though it turns out it can only go to 100000, not 200000 like the manufacturer insisted - so the effort wasn't totally wasted). This issue went undetected for MONTHS! (it's the desk lamp)

If Espruino is supposed to be a user friendly platform, it needs to warn people when they do this - not continue on it's merry way and ignore arguments they passed in. The current behavior is not what people would expect. This behavior has screwed *me* over so many times - imagine what it must be like for a novice to run into this!

**Comment by gfwilliams** [comment]
There actually is that 'general purpose function' available now (I think it might be used for SPI?) so it shouldn't be too painful to use for I2C too. I'll see what can be done.
