### ISSUE TITLE
CAN support

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#59]
Not a big deal for most users - but some people have asked about Espruino for CAN bus in cars...

**Comment by Stradivario** [comment]
Hey guys any news regarding support for CAN ? 

I am trying now to connect my Webasto Heater using Espruino and i am not sure how to deal with it.

I have a diagnostics cable for Webasto with their software which connects pretty well but i would like to read data and send data using Espruino.


I have found out that i need MCP2515 in order to connect Espruino with CAN line  but i need to order it to check it out.
I have check also one discussion from before 9 years found in Espruino forum http://forum.espruino.com/conversations/223/

I really don't know from where to start actually and how i can read out data from the heater itself. 

I didn't find also anything related with CAN, K-Line, W-Bus, K-Bus inside the espruino documentation.

Any guidance onto this topic and how to do it ? 

Thanks in advance!

Best regards,
Kristiyan Tachev 

@gfwilliams
