### ISSUE TITLE
save() issue?

### ISSUE THREAD

**Issue by tve** [espruino/Espruino#884]
I just tried save() on an esp8266 with a large amount of stuff and it resulted in errors. Yesterday I saw something similar with a small program and I had to save() a second time to make it work. Someone mentioned weird stuff on a micro:bit in a forum post http://forum.espruino.com/conversations/290264/#comment13117991. Is there something amiss?

The errors I got are:
```
{ "free": 628, "usage": 972, "total": 1600, "history": 535 }
=undefined
>save()
=undefined
Erasing Flash.....
Writing...................
ERROR: Too big to save to flash (17044 vs 12284 bytes)
Deleting command history and trying again...
Erasing Flash.....
Writing............
Compressed 25600 bytes to 10116
Checking...
There were 13 errors!
Running onInit()...
```
Is it expected that save() runs onInit()?

The micro:bit errors are:
```
Erasing Flash...
Writing...
ERROR: Too big to save to flash (244 vs -4 bytes)
Deleting command history and trying again...
Erasing Flash...
Writing...
ERROR: Too big to save to flash (163 vs -4 bytes)
```

**Comment by gfwilliams** [comment]
I think the two could be different. The micro:bit is almost certainly because the nRF5x SDK changed and some addresses have got messed up.

Not sure what's the problem with your stuff. The 'try again' thing is expected if you have too much code to compress down, but I guess maybe when it tries again something doesn't reset properly?

The 'errors' are when it reads flash memory after writing an tries to see if it's set to the correct thing.

**Comment by gfwilliams** [comment]
Did this ever get fixed? the micro:bit problem is definitely gone now.

**Comment by tve** [comment]
Let's close it, I haven't seen it again.
